feature/add-db-seeder
Ajbolitt76/dotnet-messenger pull request #2
Opened 2023-03-02 14:32 UTC by selezen4ever

2023-03-02 14:39 UTC, selezen4ever commented
JWT-токены по seed-данным пользователей в разделе Wiki

2023-03-03 07:32 UTC, Ajbolitt76 commented
> JWT-токены по seed-данным пользователей в разделе Wiki

Токены имеют неправильную структуру.

2023-03-03 07:56 UTC, Ajbolitt76 requested changes

2023-03-03 07:56 UTC, Ajbolitt76 commented on backend/Messenger/Messenger.Data/Seeder/IDbSeeder.cs
> +    Task Seed(IDbContext dbContext);
SeedAsync

2023-03-03 07:56 UTC, Ajbolitt76 commented on backend/Messenger/Messenger.Data/Seeder/DbSeeder.cs
> +                IdentityUserId = new Guid("a293d683-cf18-41db-a1d3-fcc4ce65b306")
Ты создал только бизнес представление пользователя, а нужно еще к этому добавить Identity пользователя. См UserStore.

2023-03-06 13:04 UTC, Ajbolitt76 requested changes

2023-03-06 13:04 UTC, Ajbolitt76 commented on backend/Messenger/Messenger.Data/Seeder/DbSeeder.cs
> +        var appUsers = new (string name, Guid id)[]
В кортежах мы название элемента пишем с большой буквы
```suggestion
        var appUsers = new (string Name, Guid Id)[] 
```

2023-03-06 13:06 UTC, Ajbolitt76 approved these changes

2023-03-06 13:07 UTC, merged