[NET-58] API Создания групповых чатов
Ajbolitt76/dotnet-messenger pull request #3
Opened 2023-03-04 14:51 UTC by W1ngshot

2023-03-04 18:34 UTC, Ajbolitt76 requested changes

2023-03-04 18:34 UTC, Ajbolitt76 commented on backend/Messenger/Messenger.Core/Model/ConversationAggregate/Members/BaseMember.cs
> +public abstract class BaseMember : BaseEntity
А у каких видов переписки еще будут участники?

2023-03-04 18:34 UTC, Ajbolitt76 commented on backend/Messenger/Messenger.Core/Model/ConversationAggregate/Permissions/GroupMemberPermissions.cs
> +public enum GroupMemberPermissions
```suggestion
[Flags]
public enum GroupMemberPermissions
```

2023-03-04 18:34 UTC, Ajbolitt76 commented on backend/Messenger/Messenger.Data/Migrations/20230304135451_Initial.cs
>      {
Что тут произошло? Не очень хорошо оверрайдить миграцию, которая уже в main

2023-03-04 18:34 UTC, Ajbolitt76 commented on backend/Messenger/Messenger.Data/Configuration/ConversationAggregate/Members/GroupChatMemberConfiguration.cs
> +            .HasForeignKey(x => x.ConversationId);
Я не особо уверен за навигационные поля, в них пока нет нужды, и я думаю не появится. Давай пока уберем, а потом по нужде добавим.

2023-03-04 18:34 UTC, Ajbolitt76 commented on backend/Messenger/Modules/Messenger.Conversations.GroupChats/Features/CreateGroupChat/CreateGroupChatCommand.cs
> +) : ICommand<CreatedResponse<Guid>>;
```suggestion
    string Name) : ICommand<CreatedResponse<Guid>>;
```
Последняя скобка остается на линии

2023-03-04 18:34 UTC, Ajbolitt76 commented on backend/Messenger/Modules/Messenger.Conversations.GroupChats/Features/CreateGroupChat/CreateGroupChatCommandHandler.cs
> +            Permissions = 127,
Давай отдельный класс с static readonly field сделаем? Например GroupChatPermissionPresets.Creator

2023-03-04 18:34 UTC, Ajbolitt76 commented on backend/Messenger/Modules/Messenger.Conversations.GroupChats/Features/CreateGroupChat/CreateGroupChatCommandHandler.cs
> +                Permissions = 15
GroupChatPermissionPresets.NewMember

2023-03-04 19:03 UTC, W1ngshot commented on backend/Messenger/Messenger.Core/Model/ConversationAggregate/Members/BaseMember.cs
> +public abstract class BaseMember : BaseEntity
Ну изначально я думал что это пригодится при создании каналов

2023-03-04 19:05 UTC, W1ngshot commented on backend/Messenger/Modules/Messenger.Conversations.GroupChats/Features/CreateGroupChat/CreateGroupChatCommandHandler.cs
> +            Permissions = 127,
Да, звучит как хорошая идея

2023-03-04 19:06 UTC, W1ngshot commented on backend/Messenger/Messenger.Data/Migrations/20230304135451_Initial.cs
>      {
Кхм... Постараюсь исправить и вернуть как было

2023-03-04 20:50 UTC, W1ngshot commented on backend/Messenger/Messenger.Core/Model/ConversationAggregate/Members/BaseMember.cs
> +public abstract class BaseMember : BaseEntity
Если для каналов не нужно, то переделаю

2023-03-05 09:35 UTC, Ajbolitt76 approved these changes

2023-03-05 09:35 UTC, merged